public with sharing class APX_Cieyh_01 {
    
     public static void tempo() {
        System.Debug('>> i am APX_Cieyh_01');
        System.Debug('>> i am APX_Cieyh_01');
        System.Debug('>> i am APX_Cieyh_01');
        System.Debug('>> i am APX_Cieyh_01');
        System.Debug('>> i am APX_Cieyh_01');
        System.Debug('>> i am APX_Cieyh_01');
        System.Debug('>> i am APX_Cieyh_01');
        System.Debug('>> i am APX_Cieyh_01');
        System.Debug('>> i am APX_Cieyh_01');
        System.Debug('>> i am APX_Cieyh_01');
        System.Debug('>> i am APX_Cieyh_01');
        System.Debug('>> i am APX_Cieyh_01');
        System.Debug('>> i am APX_Cieyh_01');
        Integer a;
        Integer b;
        Integer c;
        Integer d;
        Integer e;
        Integer f;
        Integer g;
    }
}

